# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 339116cfab2eeb85793787a416027325b9c0eca6f2d58e8f0dd1883a766734260cabbdd6a8bc009b0b574979b2eaca2672ac1d1e73947e614ca4fdbaeb6ea322

test:
  secret_key_base: 3a284960bc842b0a506b9ca4e43a883be79f5033ba9de69ec4b1ed9fc6fca23dedfc4162cefe249ca1066a6ef23adfa9909b25d19d505629a9a86c84dbc07ec0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
